[Core] Fix invalid cast after thawing FileService events
When different FileService event types (e.g. copy followed by a
change event) occurred when the FileService was frozen on thawing
the attempt to merge similar events together would fail since the
cast to EventData<TArgs> would not work for different event types.

System.InvalidCastException: Specified cast is not valid.
  at MonoDevelop.Core.EventQueue+EventData`1[TArgs].ShouldMerge (MonoDevelop.Core.EventQueue+EventData other) in
main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs:865
  at MonoDevelop.Core.EventQueue.Thaw ()